# TODO change mysql port so that it doesn't cause problems with another mysql running on the vm
version: "3.7"
services:
  app:
    build: 
        context: .
    links:
      - db
    ports:
      - "8080:8080"
  db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: 'urcpp_flask'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'urcpp-flask'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'DanforthLabor123!'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
      volumes:
        - ./docker/data/db:/var/lib/mysql
        - ./database/docker_init:/docker-entrypoint-initdb.d
