site_name: My Docs
pages:
  - Home: index.md
  - Components:
    - Flask: flask.md
    - Aja: aja.md
  - Development Guide:
      - Python: dev/python.md
      - Javascript: dev/js.md
  - About: about.md

theme: readthedocs
