database: "data/urcpp.sqlite"

models:
  - Faculty
  - LDAPFaculty
  - Collaborators
  - Projects
  - FacultyProjects

log:
  filename: "urcpp.log"

# Use this for URL construction.
# /{tag}/...
tag: "urcpp"

timeout: 10