urcpp:
  applicationCycle: 2016
  possibleDurations:
    - 8
    - 10
    
databases:
  dynamic: "data/urcpp.sqlite"
  static: "data/static.sqlite"

models:
  static:
    - LDAPFaculty
    - LDAPStudents
    - Programs
  dynamic:
    - Budget
    - Collaborators
    - Parameters
    - PostSurvey
    - PreSurvey
    - Projects
    - URCPPFaculty
    - URCPPStudents
    
log:
  filename: "urcpp.log"

# Use this for URL construction.
# /{tag}/...
tag: "urcpp"

timeout: 10

projectStatus:
  accept: Accept
  reject: Reject
  withdrawn: Withdrawn
  # This means they have not yet hit "Submit"
  incomplete: Incomplete
  # This means they are done, but not reviewed
  pending: Pending

response:
  badUsername: "Bad Username"
  noResults: "No Results"

filepaths:
  directory: "api/static/files/%%applicationCycle%%/%%username%%"
  allowedFileExtensions:
    rtf: "Rich Text Format"
    pdf: "Portable Document Format"
    doc: "Old Word"
    docx: "New Word"
    odt: "Libre Office"
  allowedFileNames:
    - vitae
    - narrative
    - irb
  pageTemplates: "api/templates"
  
# We don't know if these are needed, but they do document the 
# directory paths/layout that we intend...
#  filesInDirectory:
#    vitae: "%%username%%-vitae.%%thing%%"
#    narrative: "%%username%%-narrative.%%thing%%"
#    irb: "%%username%%-irb.%%thing%%"
  