urcpp:
  applicationCycle: 2016
  possibleDurations:
    - 8
    - 10
    
databases:
  dynamic: "data/urcpp.sqlite"
  static: "data/static.sqlite"

models:
  static:
    - LDAPFaculty
    - LDAPStudents
    - Programs
  dynamic:
    - URCPPFaculty
    - URCPPStudents
    - PreSurvey
    - PostSurvey
    - Projects
    - Budget
    - Parameters
    
log:
  filename: "urcpp.log"

# Use this for URL construction.
# /{tag}/...
tag: "urcpp"

timeout: 10

projectstatus:
  accept: Accept
  reject: Reject
  withdrawn: Withdrawn
  # This means they have not yet hit "Submit"
  incomplete: Incomplete
  # This means they are done, but not reviewed
  pending: Pending

response:
  badUsername: "Bad Username"
  noResults: "No Results"

filepaths:
  directory: "api/static/%%applicationCycle%%/%%username%%"
  vitae: "%%username%%-vitae.%%thing%%"
  narrative: "%%username%%-narrative.%%thing%%"
  irb: "%%username%%-irb.%%thing%%"
  