# Changes made to this file require a service restart
DEBUG:
  user: "jadudm"

urcpp:
  applicationCycle: 2016
  possibleDurations:
    - 8
    - 9
    - 10

# Controls the history.html page options for previous years funded by URCPP 
history:
  - db: "oneyr"
    desc: "Last year"
  - db: "twoyr"
    desc: "2 years ago"
  - db: "threeToFiveyr"
    desc: "3-5 years ago"
  - db: "sixToTenyr"
    desc: "6-10 years ago"
  - db: "elevenPlus"
    desc: "11+ years ago"

# NO MAS, sorta; Still need this to get through the upload sequence
# Scott: Changed the order to history, irbyn, irb(if yes), vitae, narrative, done.
# Makes the upload sequence less painful as all three are together, which is important 
# for technical reasons, not usability.  
flow:
  start:        "create"
  create:       "people"
  people:       "history"
  history:      "irbyn"
  irbyn:        "upload/irb"
  irb:          "upload/vitae"
  vitae:        "upload/narrative"
  narrative:    "budget"
  budget:       "done"
  done:         "start"
# END NO MAS

# Controls the table columns in the allProjects.html table
allProjectsTable:
  - title: "Duration"
    fieldName: "duration"
  - title: "Start Date"
    fieldName: "startDate"
  - title: "Comm. Service"
    fieldName: "isServiceToCommunity"
  - title: "Comm. Partner"
    fieldName: "hasCommunityPartner" # Will this work with two?
  - title: "# Students"
    fieldName: "numberStudents"
  - title: "Created"
    fieldName: "createdDate"
  - title: "Status"
    fieldName: "status"

# Controls the menu for the committee interfaces
committee:
  - title: "Projects"
    link: "allProjects"
    longtitle: "View all Projects"
  - title: "Files"
    link: "allFiles"
    longtitle: "View all Files"
  - title: "Budgets"
    link: "allBudgets"
    longtitle: "View all Budgets"
  - title: "Labor"
    link: "allLabor"
    longtitle: "View all Labor Allocations"
  - title: "Voting"
    link: "vote"
    longtitle: "Vote on Submissions"
  - title: "Review Votes"
    link: "allVotes"
    longtitle: "Review Votes"
    
# Controls the menu for the chair interface
chair:
  - title: "Set Parameters"
    link: "setParameters"
    longtitle: "Set URCPP Parameters"
  - title: "Manage Committee Members"
    link: "manageCommittee"
    longtitle: "Manage URCPP Committee Members"
# Controls the table columns for the voting interface
voting:
  - title: "URCPP Goals"
    dbName: "urcppGoalsVote"
    longDescription: "How well does the proposal satisfy the four URCPP goals (enhance student learning, foster student/faculty interaction, enhance student communication skills, and provide high-impact experience)"
  - title: "Project Details"
    dbName: "projectDetailsVote"
    longDescription: "How well does the proposal outline the project's background, design, goals, and methods"
  - title: "Faculty Role(s)"
    dbName: "facultyRoleVote"
    longDescription: "How well does the proposal outline the faculty's role(s)"
  - title: "Student Role(s)"
    dbName: "studentRoleVote"
    longDescription: "How well does the proposal outline the student's role(s)"
  - title: "Feasible Schedule Frame"
    dbName: "feasibilityVote"
    longDescription: "How feasible is this project?"
    

# I think this should move to the Parameters table, so it can be more easily configured in the UI by the committee.
contacts:         
  irbChairName: "Dan Huck"
  irbChairEmail: "huckd@berea.edu"

# Controls the budget.html form 
budget:
  - title: "Faculty Stipend(s) "
    placeholder: "Indicate the amount each faculty member will receive as a stipend, up to $5,300 per faculty member"
    amountFieldName: "facultyStipend"
    descFieldName: "facultyStipendDesc"
  - title: "Equipment "
    placeholder: "Indicate the equipment you will need to purchase for your research"
    amountFieldName: "equipment"
    descFieldName: "equipmentDesc"
  - title: "Materials "
    placeholder: "Indicate the materials and supplies you know will be needed to conduct your research."
    amountFieldName: "materials"
    descFieldName: "materialsDesc"
  - title: "Travel "
    placeholder: "Describe the types of travel necessary to conduct the research (airfare, hotel, etc.). Exclude any travel done by car (see the next section)"
    amountFieldName: "otherTravel"
    descFieldName: "otherTravelDesc"
  - title: "Miles "
    placeholder: "Describe the miles you and students will be traveling to conduct your research"
    amountFieldName: "miles"
    descFieldName: "milesDesc"
  - title: "Other "
    placeholder: "Describe any funding needed for things that do not fit into the categories above"
    amountFieldName: "other"
    descFieldName: "otherDesc"
    
databases:
  dynamic: "data/urcpp.sqlite"
  static: "data/static.sqlite"

models:
  static:
    - LDAPFaculty
    - LDAPStudents
    - Programs
  dynamic:
    - Budget
    - Collaborators
    - Parameters
    - PostSurvey
    - PreSurvey
    - Projects
    - URCPPFaculty
    - URCPPStudents
    - Voting
    
log:
  filename: "urcpp.log"

# Use this for URL construction.
# /{tag}/...
tag: "urcpp"

timeout: 10

projectStatus:
  accept: Accept
  reject: Reject
  withdrawn: Withdrawn
  # This means they have not yet hit "Submit"
  incomplete: Incomplete
  # This means they are done, but not reviewed
  pending: Pending

response:
  badUsername: "Bad Username"
  noResults: "No Results"

filepaths:
  directory: "api/static/files/%%applicationCycle%%/%%username%%"
  allowedFileExtensions:
    rtf: "Rich Text Format"
    pdf: "Portable Document Format"
    doc: "Old Word"
    docx: "New Word"
    odt: "Libre Office"
  allowedFileNames:
    - vitae
    - narrative
    - irb
  pageTemplates: "api/templates"
  
# We don't know if these are needed, but they do document the 
# directory paths/layout that we intend...
#  filesInDirectory:
#    vitae: "%%username%%-vitae.%%thing%%"
#    narrative: "%%username%%-narrative.%%thing%%"
#    irb: "%%username%%-irb.%%thing%%"
  
