databases:
  dynamic: "data/urcpp.sqlite"
  static: "data/static.sqlite"

models:
  dynamic:
    - Faculty
    - Projects
    - FacultyProjects
  static:
    - LDAPFaculty
    
log:
  filename: "urcpp.log"

# Use this for URL construction.
# /{tag}/...
tag: "urcpp"

timeout: 10
