# Changes made to this file require a service restart
DEBUG:
  user: "jadudm"

urcpp:
  applicationCycle: 2016
  possibleDurations:
    - 8
    - 9
    - 10

# Controls the history.html page options for previous years funded by URCPP 
history:
  - db: "oneyr"
    desc: "Last year"
  - db: "twoyr"
    desc: "2 years ago"
  - db: "threeToFiveyr"
    desc: "3-5 years ago"
  - db: "sixToTenyr"
    desc: "6-10 years ago"
  - db: "elevenPlus"
    desc: "11+ years ago"

# NO MAS, sorta; Still need this to get through the upload sequence
# Scott: Changed the order to history, irbyn, irb(if yes), vitae, narrative, done.
# Makes the upload sequence less painful as all three are together, which is important 
# for technical reasons, not usability.  
flow:
  start:        "create"
  create:       "people"
  people:       "history"
  history:      "irbyn"
  irbyn:        "upload/irb"
  irb:          "upload/vitae"
  vitae:        "upload/narrative"
  narrative:    "budget"
  budget:       "done"
  done:         "start"
# END NO MAS

# Controls the table columns in the allProjects.html table
allProjectsTable:
  - title: "Duration"
    fieldName: "duration"
  - title: "Start Date"
    fieldName: "startDate"
  - title: "End Date"
    fieldName: "endDate"
  - title: "Comm. Service"
    fieldName: "isServiceToCommunity"
  - title: "Comm. Partner"
    fieldName: "hasCommunityPartner" # Will this work with two?
  - title: "# Students"
    fieldName: "numberStudents"
  - title: "Created"
    fieldName: "createdDate"
  - title: "Status"
    fieldName: "status"

# Controls the menu for the committee interfaces
committee:
  - title: "Projects"
    link: "allProjects"
    longtitle: "View all Projects"
  - title: "Files"
    link: "allFiles"
    longtitle: "View all Files"
  - title: "Budgets"
    link: "allBudgets"
    longtitle: "View all Budgets"
  - title: "Labor"
    link: "allLabor"
    longtitle: "View all Labor Allocations"
  - title: "Review Votes"
    link: "allVotes"
    longtitle: "Review Votes"
    
# Controls the menu for the chair interface
chair:
  - title: "Set Parameters"
    link: "setParameters"
    longtitle: "Set URCPP Parameters"
  - title: "Manage Committee Members"
    link: "manageCommittee"
    longtitle: "Manage URCPP Committee Members"
# Controls the table columns for the voting interface
voting:
  - title: "Likelihood of Enhancing Student Learning"
    dbName: "studentLearning"
    longDescription: "Enhances students' learning by providing opportunities for the engagement of challenging, collaborative and directed projects in an apprentice-mentor relationship with faculty."
  - title: "Accessibility of Research to Students"
    dbName: "studentAccessibility"
    longDescription: "The project topic/material is accessible to students, allowing them to play a central role in carrying out, interpreting, and presenting the research."
  - title: "Professional Quality of Research"
    dbName: "qualityOfResearch"
    longDescription: "The project itself, not the work expected from students, should be at a level expected of faculty professionals, which allows the faculty mentor to provide a model for engaging research and creative activity."
  - title: "Potential for Career and Personal Development (Student)"
    dbName: "studentDevelopment"
    longDescription: "Offers experiences that allow students to build their self-confidence to pursue careers and make informed career and graduate school decisions for further study beyond Berea."
  - title: "Potential for Career and Personal Development (Faculty)"
    dbName: "facultyDevelopment"
    longDescription: "Offers experiences that allow faculty to strengthen their own professional development and growth."
  - title: "Collaborative Nature of Project"
    dbName: "collaborative"
    longDescription: "Helps students understand the critical interplay between collaboration and independent thought and action in any team effort to engage a complex, open-ended project."
  - title: "Level of Expected Student-Faculty Interaction"
    dbName: "interaction"
    longDescription: "Fosters significant student-faculty interaction in scholarly/creative work."
  - title: "Likelihood of Enhancing Communication Skills"
    dbName: "communication"
    longDescription: "Enhances students' communication skills by participating in a significant way in the writing of a final summary or paper reporting the methods used and interpreting the reults/conclusions of the study/project."
  - title: "Scholarly/Creative Significance"
    dbName: "scholarlySignificance"
    longDescription: "Proposal contains adequate background information establishing possible contributions of the faculty/student research to the current body of knowledge in the area of interest."
  - title: "Clarity/Quality of Proposal"
    dbName: "proposalQuality"
    longDescription: "Proposal is written in clear and concise language that is understandable by colleagues outside the discipline. Overall appearance of the proposal is professional and complete."
  - title: "Budget (Appropriateness and Justification"
    dbName: "budget"
    longDescription: "Budget is realistic, as well as justified by and consistent with the scope of the proposed project."
  - title: "Timeline"
    dbName: "timeline"
    longDescription: "There is a high probability that the proposed project will be completed within the time frame specified."
    

# I think this should move to the Parameters table, so it can be more easily configured in the UI by the committee.
contacts:         
  irbChairName: "Dan Huck"
  irbChairEmail: "huckd@berea.edu"

# Controls the budget.html form 
budget:
  - title: "Faculty Stipend(s) "
    placeholder: "Indicate the amount each faculty member will receive as a stipend, up to $5,300 per faculty member"
    amountFieldName: "facultyStipend"
    descFieldName: "facultyStipendDesc"
  - title: "Equipment "
    placeholder: "Indicate the equipment you will need to purchase for your research"
    amountFieldName: "equipment"
    descFieldName: "equipmentDesc"
  - title: "Materials "
    placeholder: "Indicate the materials and supplies you know will be needed to conduct your research."
    amountFieldName: "materials"
    descFieldName: "materialsDesc"
  - title: "Travel "
    placeholder: "Describe the types of travel necessary to conduct the research (airfare, hotel, etc.). Exclude any travel done by car (see the next section)"
    amountFieldName: "otherTravel"
    descFieldName: "otherTravelDesc"
  - title: "Miles "
    placeholder: "Describe the miles you and students will be traveling to conduct your research"
    amountFieldName: "miles"
    descFieldName: "milesDesc"
  - title: "Other "
    placeholder: "Describe any funding needed for things that do not fit into the categories above"
    amountFieldName: "other"
    descFieldName: "otherDesc"
    
databases:
  dynamic: "data/urcpp.sqlite"
  static: "data/static.sqlite"

models:
  static:
    - LDAPFaculty
    - LDAPStudents
    - Programs
  dynamic:
    - Budget
    - Collaborators
    - Parameters
    - PostSurvey
    - PreSurvey
    - Projects
    - URCPPFaculty
    - URCPPStudents
    - Voting
    - ApplicationCycle
    
log:
  filename: "urcpp.log"

# Use this for URL construction.
# /{tag}/...
tag: "urcpp"

timeout: 10

projectStatus:
  accept: Accept
  reject: Deny
  withdrawn: Withdrawn
  # This means they have not yet hit "Submit"
  incomplete: Incomplete
  # This means they are done, but not reviewed
  pending: Pending

response:
  badUsername: "Bad Username"
  noResults: "No Results"

filepaths:
  # directory: "/var/www/html/urcpp-flask/api/static/files/%%applicationCycle%%/%%username%%"
  # projectFiles: "/var/www/html/urcpp-flask/api/static/files/"
  directory: "api/static/files/%%applicationCycle%%/%%username%%"
  projectFiles: "api/static/files/"
  downloadFiles: "static/files/"
  
  allowedFileExtensions:
    rtf: "Rich Text Format"
    pdf: "Portable Document Format"
    doc: "Old Word"
    docx: "New Word"
    odt: "Libre Office"
  allowedFileNames:
    - vitae
    - narrative
    - irb
  pageTemplates: "/var/www/html/urcpp-flask/api/templates"
  
downloads:
  downloadFileTypes:
    allProjects: "project"
    allBudgets: "budget"
    allLabor: "labor"
  downloadFileNameFormat: "urcpp-%%applicationCycle%%-%%downloadFileType%%"
  downloadFileExtension: ".xlsx"
  
# We don't know if these are needed, but they do document the 
# directory paths/layout that we intend...
#  filesInDirectory:
#    vitae: "%%username%%-vitae.%%thing%%"
#    narrative: "%%username%%-narrative.%%thing%%"
#    irb: "%%username%%-irb.%%thing%%"
  
