databases:
  dynamic: "data/urcpp.sqlite"
  static: "data/static.sqlite"

models:
  static:
    - LDAPFaculty
    - LDAPStudents
    - Programs
  dynamic:
    - URCPPFaculty
    - URCPPStudents
    - PreSurvey
    - PostSurvey
    - Projects
    - Budget
    - Parameters
    
log:
  filename: "urcpp.log"

# Use this for URL construction.
# /{tag}/...
tag: "urcpp"

timeout: 10

projectstatus:
  - Accept
  - Reject
  - Withdrawn