urcpp:
  applicationCycle: 2016
  possibleDurations:
    - 8
    - 10

history:
  - db: "oneyr"
    desc: "Last year"
  - db: "twoyr"
    desc: "2 years ago"
  - db: "threeToFiveyr"
    desc: "3-5 years ago"
  - db: "sixToTenyr"
    desc: "6-10 years ago"
  - db: "elevenPlus"
    desc: "11+ years ago"

# NO MAS; Still need this to get through the upload sequence
# Scott: Changed the order to history, irbyn, irb(if yes), vitae, narrative, done.
# Makes the upload sequence less painful as all three are together, which is important 
# for technical reasons, not usability.  
flow:
  start:        "create"
  create:       "people"
  people:       "history"
  history:      "irbyn"
  irbyn:        "upload/irb"
  irb:          "upload/vitae"
  vitae:        "upload/narrative"
  narrative:    "done"
  done:         "start"
# END NO MAS

contacts:
  irbChairName: "Dan Huck"
  irbChairEmail: "huckd@berea.edu"
  
budget:
  - title: "Faculty Stipend "
    placeholder: "Indicate the amount each faculty member will receive as a stipend, up to $5,300"
    amountFieldName: "facultyStipend"
    descFieldName: "facultyStipendDesc"
  - title: "Equipment "
    placeholder: "Indicate the equipment you will to conduct your research"
    amountFieldName: "equipment"
    descFieldName: "equipmentDesc"
  - title: "Materials "
    placeholder: "Indicate the materials and supplies you know will be needed to conduct your research."
    amountFieldName: "materials"
    descFieldName: "materialsDesc"
  - title: "Travel "
    placeholder: "Describe the types of travel necessary to conduct the research (airfare, hotel, etc.). Exclude any travel done by car (see the next section)"
    amountFieldName: "otherTravel"
    descFieldName: "otherTravelDesc"
  - title: "Miles "
    placeholder: "Describe the miles you and students will be traveling to conduct your research"
    amountFieldName: "miles"
    descFieldName: "milesDesc"
  - title: "Other "
    placeholder: "Describe any funding needed for things that do not fit into the categories above"
    amountFieldName: "other"
    descFieldName: "otherDesc"
    
databases:
  dynamic: "data/urcpp.sqlite"
  static: "data/static.sqlite"

models:
  static:
    - LDAPFaculty
    - LDAPStudents
    - Programs
  dynamic:
    - Budget
    - Collaborators
    - Parameters
    - PostSurvey
    - PreSurvey
    - Projects
    - URCPPFaculty
    - URCPPStudents
    
log:
  filename: "urcpp.log"

# Use this for URL construction.
# /{tag}/...
tag: "urcpp"

timeout: 10

projectStatus:
  accept: Accept
  reject: Reject
  withdrawn: Withdrawn
  # This means they have not yet hit "Submit"
  incomplete: Incomplete
  # This means they are done, but not reviewed
  pending: Pending

response:
  badUsername: "Bad Username"
  noResults: "No Results"

filepaths:
  directory: "api/static/files/%%applicationCycle%%/%%username%%"
  allowedFileExtensions:
    rtf: "Rich Text Format"
    pdf: "Portable Document Format"
    doc: "Old Word"
    docx: "New Word"
    odt: "Libre Office"
  allowedFileNames:
    - vitae
    - narrative
    - irb
  pageTemplates: "api/templates"
  
# We don't know if these are needed, but they do document the 
# directory paths/layout that we intend...
#  filesInDirectory:
#    vitae: "%%username%%-vitae.%%thing%%"
#    narrative: "%%username%%-narrative.%%thing%%"
#    irb: "%%username%%-irb.%%thing%%"
  