# FIXME: We will want to move salts
# out of this into a config that is not
# committed to the repository. For development,
# this does not matter.
salts:
  bnumber: "MTEyYjc3Nzk1ZGFjYjVkYWNkYmJkZDI1"

# Linux
# date +%s | sha256sum | base64 | head -c 32 ; echo
# Mac OSX
# date +%s | shasum -a 256 | base64 | head -c 32 ; echo
secret_key: "OTE1YWMyYzgxMDFlZmMzYjY3MjdlNzU3"
